### ISSUE TITLE
Black screen after configuring MMM-FreeBox-Monitor

### ISSUE THREAD

**Issue by mpetit** [tataille/MMM-FreeBox-Monitor#1]
Hello,

I just tested your Freebox module.
After setting the IP address ( _IP : 192.168.1.254_ ) on my freebox in the config.js file and recharge MM2 , I've got a black screen.

can you help me?

**Comment by tataille** [comment]
Hello

Could you check the console logs for magicmirror. And copy them in the thread ?

**Comment by tataille** [comment]
I'm not sure but where did you get the Freebox IP?
I think by default it is 192.168.0.254

**Comment by mpetit** [comment]
hello, 

vive la france, 
by the way my freebox ip address is truly 192.168.1.254
i had a problem at the freebox module configuration that i fixed, but since i have a blank screen.
my freebox module configuration

```
    {
                    module: 'MMM-FreeBox-Monitor',
                    position: 'top_left',   // This can be any of the regions. Best results in left or right regions.
                    config: {
                    mirrorName: "My Magic Mirror",
                    ip: '192.168.1.254'
                    }
            },
```

**Comment by tataille** [comment]
Ouais vive la France!

Did you check the Freebox Server lcd screen?
What are the logs in console?
I mean you should see something like... authorization pending?
Another thing to check is the debug info in the mirror screen ctrl + shift
- I
  Le 7 juil. 2016 11:36 PM, "mpetit" notifications@github.com a écrit :

hello,

vive la france,
by the way my freebox ip address is truly 192.168.1.254
i had a problem at the freebox module configuration that i fixed, but since
i have a blank screen.
my freebox module configuration

```
{
                module: 'MMM-FreeBox-Monitor',
                position: 'top_left',   // This can be any of the
```

regions. Best results in left or right regions.
                    config: {
                    mirrorName: "My Magic Mirror",
                    ip: '192.168.1.254'
                    }
            },

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/tataille/MMM-FreeBox-Monitor/issues/1#issuecomment-231214824,
or mute the thread
https://github.com/notifications/unsubscribe/ATMWGES4VRRj8WUMYhUwF98Pc5lJqquVks5qTXFtgaJpZM4JGg5g
.

**Comment by tataille** [comment]
Is it OK?

**Comment by mpetit** [comment]
Lcd screen : nothing
errors 
**mm-error-log**
{ Error: Cannot find module 'parse-torrent-name'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/freeboxapi.js:16:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12) code: 'MODULE_NOT_FOUND' }'

**Comment by tataille** [comment]
Fixed. Could you retry? Download module -> npm install

**Comment by mpetit** [comment]
same error

Error: Cannot find module 'parse-torrent-name'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/freeboxapi.js:16:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
{ Error: Cannot find module 'parse-torrent-name'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/freeboxapi.js:16:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12) code: 'MODULE_NOT_FOUND' }

**Comment by tataille** [comment]
Did you get the latest package.json file and type "npm install" ? can you show me your package.json

**Comment by mpetit** [comment]
{
  "name": "magic-mirror-module-freeboxmonitor",
  "version": "1.0.0",
  "description": "A Freebox monitor module for Magic Mirror",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/tataille/MMM-FreeBox-Monitor.git"
  },
  "keywords": [
    "magic mirror",
    "smart mirror",
    "freebox",
    "monitor"
  ],
  "dependencies": {
    "request-json": "latest",
    "imdb-api": "latest",
    "omdb": "latest",
    "crypto-js": "latest",
    "fs": "latest",
    "underscore": "latest",
    "moment": "latest"
    },
  "author": "Jean-Marc Taillant",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/tataille/MMM-FreeBox-Monitor/issues"
  },
  "homepage": "https://github.com/tataille/MMM-FreeBox-Monitor#readme"
}

**Comment by tataille** [comment]
You didn't get the latest version of package.json file. Dependencies should include:

 "dependencies": {
    "request-json": "latest",
    "imdb-api": "latest",
    "omdb": "latest",
    "crypto-js": "latest",
    "fs": "latest",
    "underscore": "latest",
    "moment": "latest",
    **"parse-torrent-name": "latest"**
    }

**Comment by mpetit** [comment]
no more error,

for now i'm at work, i'll check later on the freebox lcd screen.

thank's

**Comment by tataille** [comment]
you are welcome

**Comment by mpetit** [comment]
hello,

sorry for the delay...

try to reinstall the freebox module.
have this new error

ReferenceError: NodeHelper is not defined
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/node_helper.js:13:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at loadModule (/home/pi/MagicMirror/js/app.js:75:17)
    at loadModules (/home/pi/MagicMirror/js/app.js:92:4)
ReferenceError: NodeHelper is not defined
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/node_helper.js:13:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at loadModule (/home/pi/MagicMirror/js/app.js:75:17)
    at loadModules (/home/pi/MagicMirror/js/app.js:92:4)

**Comment by tataille** [comment]
What is the version of your Raspberry and node version (run "node -version" from command line)

**Comment by tataille** [comment]
and node

**Comment by mpetit** [comment]
v6.2.2

**Comment by tataille** [comment]
Node should be updated to latest version as stated in 

https://github.com/MichMich/MagicMirror

**Comment by mpetit** [comment]
I upgraded Node to version 6.3, same issue
after several configuration tests ,  my observations below.
Your module gives me this error message  "_NodeHelper is not defined...._
But if I put your module in the end of config.js file I have this new message
_Error happened: Error: Invalid URI "/api/v3/login/authorize/"_
voila

**Comment by tataille** [comment]
Node must be version 10

**Comment by tataille** [comment]
Forget about nodejs. Could you post you configure file?

**Comment by mpetit** [comment]
/\* Magic Mirror Config Sample
 *
- By Michael Teeuw http://michaelteeuw.nl
- MIT Licensed.
  */

var config = {
    port: 8080,

```
language: 'fr',
timeFormat: 24,
units: 'metric',

modules: [
    {
        module: 'clock',
        position: 'top_left'
    },

    {
            module: 'MMM-WunderGround',
            position: 'top_right',  // This can be any of the regions.
                                        // Best results in left or right regions.
            config: {
                // See 'Configuration options' for more information.
                apikey: 'xxxxxxxxxx', // private; don't share!
                pws: 'pws:IPARIS1168',
                lang: 'FR',
                fctext: '1',
                    fcdaycount: "5",
                fcdaystart: "0",
                hourly: '1',
                hourlyinterval: "3",
                    hourlycount: "2",
                    alerttime: 10000,
                    alerttruncatestring: "english:" // truncate the alertstring ath this word

                }
        },
```

{
    module: 'airquality',
    position: 'top_center', // you may choose any location
    config: {
        lang: 'fr',
        location: 'Paris' // the location to check the index for
    }
},

```
    {
            module: 'MMM-wordnik',
            position: 'lower_third',
            config: {
            api_key: 'xxxxxxxxxxxxxx'
     }
},

{
        module: 'compliments',
        position: 'lower_third'
    },
```

{
    module: 'MMM-Traffic',
    position: 'bottom_bar',
    classes: 'dimmed medium', //optional, default is 'bright medium', only applies to commute info not route_name
    config: {
        api_key: 'xxxxxxxx',
        mode: 'driving',
        origin: 'yyyyyyyyyyy',
        destination: 'zzzzzzzzzzzzzzz',
        route_name: 'Maison --> boulot',
        changeColor: true,
        lang: 'fr',
    showGreen: false,
        limitYellow: 5, //Greater than 5% of journey time due to traffic
        limitRed: 20, //Greater than 20% of journey time due to traffic
        traffic_model: 'best_guess',
    prependText: 'Trajet:',
        interval: 600000 //5 minutes
    }
},

```
{
        module: 'newsfeed',
        position: 'bottom_bar',
        config: {
            feeds: [
                {
                    title: "Le Monde",
                    url: "http://www.lemonde.fr/rss/une.xml"
                },
                {
                                title: "France 24",
                                url: "http://www.france24.com/fr/actualites/rss"
                        },
            ],
            showSourceTitle: true,
            showPublishDate: true
        }
    },
    {
                    module: 'mmm-systemtemperature',
                    position: 'bottom_bar', // This can be any of the regions.
                    classes: 'small dimmed', // Add your own styling. Optional.
                    config: {
        // See 'Configuration options' for more information.
    }
},
```

{
                module: 'calendar_monthly',
                position: 'top_left',
                config: {
                        // The config property is optional
                        // Without a config, a default month view is shown
                        // Please see the 'Configuration Options' section for more information
                }
            },

```
{
        module: 'calendar',
        header: 'J oFF',
        position: 'top_left',
        config: {
            calendars: [
                {
                    symbol: 'calendar-check-o ',
                    url: 'webcal://www.calendarlabs.com/templates/ical/France-Holidays.ics'
                }
            ]
        }
    },

    {
                    module: 'MMM-FreeBox-Monitor',
                    position: 'top_left',   // This can be any of the regions. Best results in left or right regions.
                    config: {
                    mirrorName: "My Magic Mirror",
                    ip: '192.168.1.254'
                        }
            },


]
```

};

**Comment by tataille** [comment]
Coud you replace " " " with single quote for mirrorName like this:

mirrorName: 'My Magic Mirror'

Thanks

2016-07-12 22:12 GMT+02:00 mpetit notifications@github.com:

**Comment by mpetit** [comment]
same error... :(

**Comment by tataille** [comment]
Replace "}," with "}" at the end and before "]"

**Comment by mpetit** [comment]
same error 

_Error happened: Error: Invalid URI "/api/v3/login/authorize/"_

**Comment by tataille** [comment]
Replace
 ip: '192.168.1.254'

With
 ip: 'http://192.168.1.254'

2016-07-13 10:23 GMT+02:00 mpetit notifications@github.com:

**Comment by mpetit** [comment]
TypeError: Cannot read property 'app_token' of undefined
    at authCallback (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/freeboxapi.js:41:43)
    at Object.parseBody (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/node_modules/request-json/main.js:153:24)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/node_modules/request/request.js:988:12)

**Comment by tataille** [comment]
Any logs in console?

2016-07-13 11:38 GMT+02:00 mpetit notifications@github.com:

**Comment by tataille** [comment]
You should see a log in console:
"AuthCallback -> xxx"

2016-07-13 11:48 GMT+02:00 Jean-Marc Taillant jean.marc.taillant@gmail.com
:

**Comment by mpetit** [comment]
ok Greeeat, the good configuration is 

**_config: {
            mirrorName: "My Magic Mirror",
            ip: "http://XXX.XXX.XXX.XXX"_**

with double quote.
nice job.

**Comment by tataille** [comment]
Merci! Feel free to improve the module...
