### ISSUE TITLE
Ecran noir

### ISSUE THREAD

**Issue by Laurent22001** [tataille/MMM-FreeBox-Monitor#9]
Bonjour,

Quand je met le module dans config.js, j'ai un écran noir, et quand je l'enlève le magic mirror refonctionne

**Comment by tataille** [comment]
> 

Des logs du serveur?

**Comment by tataille** [comment]
Quelle version du magicmirror?

**Comment by tataille** [comment]
Quelle version freebox?

**Comment by Laurent22001** [comment]
Bonjour,

où se situe les logs de MagicMirror ?

J'ai la dernière version de MM2, du module Freeebox, et la Freebox est Revolution

**Comment by Laurent22001** [comment]
voici le log mm-error:

[23.03.2022 18:54.11.455] [ERROR] ReferenceError: NodeHelper is not defined
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/node_helper.js:13:18)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at loadModule (/home/pi/MagicMirror/js/app.js:127:19)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:165:5)
[23.03.2022 18:54.11.457] [ERROR] Whoops! There was an uncaught exception...
[23.03.2022 18:54.11.461] [ERROR] ReferenceError: NodeHelper is not defined
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/node_helper.js:13:18)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at loadModule (/home/pi/MagicMirror/js/app.js:127:19)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:165:5)
[23.03.2022 18:54.11.461] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[23.03.2022 18:54.11.462] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[1235:0323/185743.855562:ERROR:connection.cc(66)] X connection error received.
rec FAIL sox: `default' Input/output error: Operation not permitted
X connection to :0 broken (explicit kill or server shutdown).
/home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
[23.03.2022 18:58.25.103] [ERROR] ^[[31mWARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: ReferenceError: NodeHelper is not defined^[[39m
^[[31m    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-FreeBox-Monitor/node_helper.js:13:18)^[[39m
^[[31m    at Module._compile (node:internal/modules/cjs/loader:1116:14)^[[39m
^[[31m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)^[[39m
^[[31m    at Module.load (node:internal/modules/cjs/loader:988:32)^[[39m
^[[31m    at Module._load (node:internal/modules/cjs/loader:829:12)^[[39m
^[[31m    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)^[[39m
^[[31m    at Module.require (node:internal/modules/cjs/loader:1012:19)^[[39m
^[[31m    at require (node:internal/modules/cjs/helpers:94:18)^[[39m
^[[31m    at loadModule (/home/pi/MagicMirror/js/app.js:127:19)^[[39m
^[[31m    at loadNextModule (/home/pi/MagicMirror/js/app.js:165:5)^[[39m
[23.03.2022 18:58.25.122] [ERROR] App threw an error during load

**Comment by Laurent22001** [comment]
Merci, 

J'ai résolu le problème en ajoutant "var NodeHelper = require("node_helper");" dans le fichier node_helper.js

**Comment by tataille** [comment]
> Correction reportée dans le code
